### PR TITLE
fix displayContentMainTableWrap 2022.07.20 23:20

### LINKED ISSUE #167: update this module with factory
https://github.com/LLazyEmail/nomoretogo_email_template/blob/9207e3a14b35015d0af97c081a4280e78e706f65/src/display/displayContentMainTableWrap.js#L1

```javascript

// TODO update this module with factory
import contentMainTableWrap from '../domain/innerTemplate/contentMainTableWrap';

try {

```

### PR DESCRIPTION
**Pull request by web4uartstudio**
1 Fix #167

### CODE REVIEW

File: sub-modules/Errors.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+class Errors {
```
Comment (atherdon) [inline sub-modules/Errors.js:1]: it wouldn't work correctly. if you want to use it at all sub-modules inside, it's better to put 3 copies inside of those package src files

File: sub-modules/innerTemplate/src/components/tableHeaderBlockLogo.js [hunk 2]
```diff
@@ -2,7 +2,7 @@
 
 // Config file
 // import { pathMainLogo } from "../../../config.js";
-import { pathMainLogo } from '../../config';
+import { pathMainLogo } from '../../../../src/config';
```
Comment (atherdon) [inline sub-modules/innerTemplate/src/components/tableHeaderBlockLogo.js:5]: let's have a copy of our config files. instead of importing them

File: sub-modules/innerTemplate/src/index.js [hunk 3]
```diff
@@ -1,3 +1,6 @@
+import topPanelViewInBrows from './components/topPanelViewInBrows';
+import tableHeaderBlockLogo from './components/tableHeaderBlockLogo';
```
Comment (atherdon) [inline sub-modules/innerTemplate/src/index.js:2]: will publish a new version of this module after merging this pull request

File: sub-modules/miscellaneous/src/components/view-in-browser-link.js [hunk 4]
```diff
@@ -1,21 +1,22 @@
 // Create view-in-brows component
+import Errors from '../../../Errors';
```
Comment (atherdon) [inline sub-modules/miscellaneous/src/components/view-in-browser-link.js:2]: mentioned this before

**Review by atherdon — APPROVED** [review]
